name: Build and Push Docker Image

on:
  push:
    branches:
      - test
      
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build and Push Microservices
        run: |
          for service in ./src/*; do
            if [ -d "$service" ] && [ -f "$service/Dockerfile" ]; then
              service_name=$(basename "$service")
              echo "Building and pushing Docker image for $service_name..."
              
              docker build -t ${{ secrets.DOCKER_USERNAME }}/$service_name:latest $service
              docker tag ${{ secrets.DOCKER_USERNAME }}/$service_name:latest ${{ secrets.DOCKER_USERNAME }}/$service_name:${{ github.sha }}
              
              docker push ${{ secrets.DOCKER_USERNAME }}/$service_name:latest
              docker push ${{ secrets.DOCKER_USERNAME }}/$service_name:${{ github.sha }}
            fi
            docker build -t ${{ secrets.DOCKER_USERNAME }}/cartservice -f ./src/cartservice/src/Dockerfile ./src/cartservice/src/
            docker tag ${{ secrets.DOCKER_USERNAME }}/cartservice:latest ${{ secrets.DOCKER_USERNAME }}/cartservice:${{ github.sha }}
            docker push ${{ secrets.DOCKER_USERNAME }}/cartservice:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/cartservice:${{ github.sha }}
          done
        
